apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.9
        volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
        ports:
        - containerPort: 8080
      volumes:
        - name: my-csi-volume
          persistentVolumeClaim:
            claimName: csi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  annotations:
   load-balancer.hetzner.cloud/location: nbg1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hello-kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes